#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/var/log/squid-service \
	/app/squid-service/client/

# download latest server
wget -O /app/squid-service/squid-service.jar https://s3-ap-southeast-2.amazonaws.com/squid-service-releases/squid-service.jar -q --show-progress

# permissions
chown -R abc:abc \
	/app

chmod 777 \
	/var/log/squid-service
